// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cdaccesscontrol/authentication_log.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticationLog struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Transaction string `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp   string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details     string `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Decision    string `protobuf:"bytes,5,opt,name=decision,proto3" json:"decision,omitempty"`
	Function    string `protobuf:"bytes,6,opt,name=function,proto3" json:"function,omitempty"`
	Recipient   string `protobuf:"bytes,7,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Creator     string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *AuthenticationLog) Reset()         { *m = AuthenticationLog{} }
func (m *AuthenticationLog) String() string { return proto.CompactTextString(m) }
func (*AuthenticationLog) ProtoMessage()    {}
func (*AuthenticationLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae31bdc8aee808b4, []int{0}
}
func (m *AuthenticationLog) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthenticationLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthenticationLog.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthenticationLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationLog.Merge(m, src)
}
func (m *AuthenticationLog) XXX_Size() int {
	return m.Size()
}
func (m *AuthenticationLog) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationLog.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationLog proto.InternalMessageInfo

func (m *AuthenticationLog) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuthenticationLog) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func (m *AuthenticationLog) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *AuthenticationLog) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *AuthenticationLog) GetDecision() string {
	if m != nil {
		return m.Decision
	}
	return ""
}

func (m *AuthenticationLog) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *AuthenticationLog) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *AuthenticationLog) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticationLog)(nil), "crossdomain.cdaccesscontrol.AuthenticationLog")
}

func init() {
	proto.RegisterFile("cdaccesscontrol/authentication_log.proto", fileDescriptor_ae31bdc8aee808b4)
}

var fileDescriptor_ae31bdc8aee808b4 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xe3, 0x50, 0xfa, 0x63, 0x24, 0x24, 0x3c, 0x59, 0x80, 0xac, 0x08, 0x96, 0x4c, 0xcd,
	0xc0, 0xcc, 0x00, 0x33, 0x53, 0x47, 0x16, 0x64, 0x6c, 0x53, 0xae, 0x94, 0xf8, 0x46, 0xf6, 0xad,
	0x04, 0x6f, 0xc1, 0x63, 0x31, 0x76, 0x64, 0x44, 0xc9, 0xcc, 0x3b, 0xa0, 0x24, 0xb4, 0xb4, 0x1d,
	0xcf, 0xf9, 0x7c, 0xfd, 0x49, 0x87, 0xe7, 0xc6, 0x6a, 0x63, 0x5c, 0x8c, 0x06, 0x3d, 0x05, 0x2c,
	0x0b, 0xbd, 0xa2, 0x57, 0xe7, 0x09, 0x8c, 0x26, 0x40, 0xff, 0x54, 0xe2, 0x72, 0x5e, 0x07, 0x24,
	0x14, 0x17, 0x26, 0x60, 0x8c, 0x16, 0x2b, 0x0d, 0x7e, 0x7e, 0x70, 0x75, 0xf5, 0xc3, 0xf8, 0xd9,
	0xdd, 0xde, 0xe5, 0x03, 0x2e, 0xc5, 0x29, 0x4f, 0xc1, 0x4a, 0x96, 0xb1, 0x7c, 0xb4, 0x48, 0xc1,
	0x8a, 0x8c, 0x9f, 0x50, 0xd0, 0x3e, 0x6a, 0xd3, 0xbd, 0x90, 0x69, 0xc6, 0xf2, 0xd9, 0x62, 0xb7,
	0x12, 0x97, 0x7c, 0x46, 0x50, 0xb9, 0x48, 0xba, 0xaa, 0xe5, 0x51, 0xcf, 0xff, 0x0b, 0x21, 0xf9,
	0xc4, 0x3a, 0xd2, 0x50, 0x46, 0x39, 0xea, 0xd9, 0x26, 0x8a, 0x73, 0x3e, 0xb5, 0xce, 0x40, 0xec,
	0xbe, 0x3d, 0xee, 0xd1, 0x36, 0x77, 0xec, 0x65, 0xe5, 0x07, 0xe5, 0x78, 0x60, 0x9b, 0xdc, 0xf9,
	0x82, 0x33, 0x50, 0x83, 0xf3, 0x24, 0x27, 0x83, 0x6f, 0x5b, 0x74, 0x3e, 0x13, 0x9c, 0x26, 0x0c,
	0x72, 0x3a, 0xf8, 0xfe, 0xe2, 0xfd, 0xed, 0x67, 0xa3, 0xd8, 0xba, 0x51, 0xec, 0xbb, 0x51, 0xec,
	0xa3, 0x55, 0xc9, 0xba, 0x55, 0xc9, 0x57, 0xab, 0x92, 0xc7, 0xeb, 0x9d, 0x99, 0x8a, 0xb7, 0xe2,
	0x70, 0x5e, 0x7a, 0xaf, 0x5d, 0x7c, 0x1e, 0xf7, 0x93, 0xde, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x76, 0x9f, 0xeb, 0xaa, 0x7e, 0x01, 0x00, 0x00,
}

func (m *AuthenticationLog) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthenticationLog) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthenticationLog) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintAuthenticationLog(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintAuthenticationLog(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Function) > 0 {
		i -= len(m.Function)
		copy(dAtA[i:], m.Function)
		i = encodeVarintAuthenticationLog(dAtA, i, uint64(len(m.Function)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Decision) > 0 {
		i -= len(m.Decision)
		copy(dAtA[i:], m.Decision)
		i = encodeVarintAuthenticationLog(dAtA, i, uint64(len(m.Decision)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Details) > 0 {
		i -= len(m.Details)
		copy(dAtA[i:], m.Details)
		i = encodeVarintAuthenticationLog(dAtA, i, uint64(len(m.Details)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintAuthenticationLog(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Transaction) > 0 {
		i -= len(m.Transaction)
		copy(dAtA[i:], m.Transaction)
		i = encodeVarintAuthenticationLog(dAtA, i, uint64(len(m.Transaction)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintAuthenticationLog(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthenticationLog(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthenticationLog(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AuthenticationLog) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovAuthenticationLog(uint64(m.Id))
	}
	l = len(m.Transaction)
	if l > 0 {
		n += 1 + l + sovAuthenticationLog(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovAuthenticationLog(uint64(l))
	}
	l = len(m.Details)
	if l > 0 {
		n += 1 + l + sovAuthenticationLog(uint64(l))
	}
	l = len(m.Decision)
	if l > 0 {
		n += 1 + l + sovAuthenticationLog(uint64(l))
	}
	l = len(m.Function)
	if l > 0 {
		n += 1 + l + sovAuthenticationLog(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovAuthenticationLog(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovAuthenticationLog(uint64(l))
	}
	return n
}

func sovAuthenticationLog(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthenticationLog(x uint64) (n int) {
	return sovAuthenticationLog(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AuthenticationLog) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthenticationLog
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthenticationLog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthenticationLog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transaction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transaction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Details = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decision", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Decision = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Function", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Function = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthenticationLog(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthenticationLog
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthenticationLog(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthenticationLog
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthenticationLog
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthenticationLog
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthenticationLog
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthenticationLog
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthenticationLog        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthenticationLog          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthenticationLog = fmt.Errorf("proto: unexpected end of group")
)
